// movegen.h — pseudo-legal move generation, move ordering, magic-bitboard attacks.
#pragma once

#include "types.h"
#include "board.h"

// One-time init of magic bitboards and pawn/knight/king attack tables.
void init_movegen();

// Attack helpers — valid only after init_movegen().
Bitboard rook_attacks(int sq, Bitboard occ);
Bitboard bishop_attacks(int sq, Bitboard occ);
inline Bitboard queen_attacks(int sq, Bitboard occ) { return rook_attacks(sq, occ) | bishop_attacks(sq, occ); }
Bitboard knight_attacks_bb(int sq);
Bitboard king_attacks_bb(int sq);
Bitboard pawn_attacks_bb(Color c, int sq);
Bitboard pawn_attacks_set(Color c, Bitboard pawns);  // attacks generated by all pawns of color

// --- Move list ---------------------------------------------------------------
struct ExtMove {
    Move move;
    int score;
    bool operator<(const ExtMove& o) const { return score > o.score; }  // sort: high score first
};

struct MoveList {
    ExtMove moves[MAX_MOVES];
    int size = 0;
    void push(Move m) { moves[size++] = { m, 0 }; }
};

void generate_legal(const Board& b, MoveList& list);
void generate_pseudo(const Board& b, MoveList& list);
void generate_captures(const Board& b, MoveList& list);  // captures + queen promotions

// Move ordering. `tt_move` may be MOVE_NONE.
void score_moves(const Board& b, MoveList& list,
                 Move tt_move,
                 const Move* killers,           // 2 entries
                 const int (*history)[64],      // [piece][to_square] -> score
                 Move counter);

// Pop the next-highest-score move from `list[start..)`, swapping it to `start`.
inline ExtMove& pick_next(MoveList& list, int start) {
    int best = start;
    for (int i = start + 1; i < list.size; i++) {
        if (list.moves[i].score > list.moves[best].score) best = i;
    }
    if (best != start) std::swap(list.moves[best], list.moves[start]);
    return list.moves[start];
}

uint64_t perft(Board& b, int depth);
