// movegen.h — pseudo-legal move generation, move ordering, magic-bitboard attacks.
#pragma once

#include "types.h"
#include "board.h"
#include <atomic>

// One-time init of magic bitboards and pawn/knight/king attack tables.
void init_movegen();

// Attack helpers — valid only after init_movegen().
Bitboard rook_attacks(int sq, Bitboard occ);
Bitboard bishop_attacks(int sq, Bitboard occ);
inline Bitboard queen_attacks(int sq, Bitboard occ) { return rook_attacks(sq, occ) | bishop_attacks(sq, occ); }
Bitboard knight_attacks_bb(int sq);
Bitboard king_attacks_bb(int sq);
Bitboard pawn_attacks_bb(Color c, int sq);
Bitboard pawn_attacks_set(Color c, Bitboard pawns);  // attacks generated by all pawns of color

// --- Move list ---------------------------------------------------------------
struct ExtMove {
    Move move;
    int score;
    bool operator<(const ExtMove& o) const { return score > o.score; }  // sort: high score first
};

struct MoveList {
    ExtMove moves[MAX_MOVES];
    int size = 0;
    void push(Move m) { moves[size++] = { m, 0 }; }
};

void generate_legal(const Board& b, MoveList& list);
void generate_pseudo(const Board& b, MoveList& list);
void generate_captures(const Board& b, MoveList& list);  // captures + all promotions
void generate_quiets(const Board& b, MoveList& list);    // non-captures, non-promotions

// Pop the next-highest-score move from `list[start..)`, swapping it to `start`.
// Used by qsearch (which generates all caps up front).
inline ExtMove& pick_next(MoveList& list, int start) {
    int best = start;
    for (int i = start + 1; i < list.size; i++) {
        if (list.moves[i].score > list.moves[best].score) best = i;
    }
    if (best != start) std::swap(list.moves[best], list.moves[start]);
    return list.moves[start];
}

// ---------------------------------------------------------------------------
// MovePicker: lazy, staged move generation for the main alpha-beta search.
//
// Stages, in order:
//   1. TT move (if pseudo-legal in this position)
//   2. Good captures (SEE > 0), MVV-LVA ordered
//   3. Killer #1
//   4. Killer #2
//   5. Equal captures (SEE == 0), MVV-LVA ordered
//   6. Quiet moves, history-ordered
//   7. Bad captures (SEE < 0), MVV-LVA ordered
// We only generate the next group when the previous one runs out without a
// beta cutoff — saving 20-30% of nodes at high depth.
// ---------------------------------------------------------------------------
class MovePicker {
public:
    enum Stage : int {
        ST_TT = 0,
        ST_GEN_CAPS, ST_GOOD_CAPS,
        ST_KILLER1, ST_KILLER2,
        ST_EQUAL_CAPS,
        ST_GEN_QUIETS, ST_QUIETS,
        ST_BAD_CAPS,
        ST_DONE
    };

    MovePicker(const Board& b,
               Move tt_move,
               const Move* killers,
               std::atomic<int> (*history)[64]);

    Move next();
    Stage stage() const { return stage_; }

private:
    const Board* b_;
    Stage stage_ = ST_TT;
    Move tt_move_, killer1_, killer2_;
    std::atomic<int> (*history_)[64];

    MoveList caps_;
    MoveList quiets_;
    int caps_idx_      = 0;
    int caps_eq_start_ = 0;
    int caps_bad_start_= 0;
    int quiets_idx_    = 0;

    void generate_and_classify_caps();
    void generate_and_score_quiets();
};

uint64_t perft(Board& b, int depth);
